# Generated by Django 6.0.1 on 2026-01-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_loginpage_alter_registration_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loginpage',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
