# Generated by Django 6.0.1 on 2026-02-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='pcateorgy',
            new_name='pcategory',
        ),
    ]
