# Generated by Django 6.0.1 on 2026-02-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_pcateorgy_cartmodel_pcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='pcategory',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='pimage',
            field=models.ImageField(default='Default.jpg', upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
